services:
  shoppinglist_sync:
    image: ghcr.io/jhns-de/shoppinglist_sync:main
    container_name: shoppinglist_sync
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - CALDAV_HOST=${CALDAV_HOST}
      - CALDAV_USER=${CALDAV_USER}
      - CALDAV_PASSWORD=${CALDAV_PASSWORD}
      - CALDAV_SHOPPING_LIST_URL=${CALDAV_SHOPPING_LIST_URL}
      - GROCY_HOST=${GROCY_HOST}
      - GROCY_TOKEN=${GROCY_TOKEN}